language: swift
os: osx
osx_image: xcode12.5
before_install:
  - swift package generate-xcodeproj
jobs:
  include:
    - stage: Test
      name: iOS Unit Tests
      script:
      - xcodebuild -project OktaSdk.xcodeproj -scheme OktaSdk-Package -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" test
