//
// PolicySubjectMatchType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum PolicySubjectMatchType: String, Codable, CaseIterable {
    case username = "USERNAME"
    case email = "EMAIL"
    case usernameOrEmail = "USERNAME_OR_EMAIL"
    case customAttribute = "CUSTOM_ATTRIBUTE"
}
