//
// ScopeType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum ScopeType: String, Codable, CaseIterable {
    case cors = "CORS"
    case redirect = "REDIRECT"
}
