//
// SecurePasswordStoreApplicationSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct SecurePasswordStoreApplicationSettings: Codable, Hashable {

    public var app: SecurePasswordStoreApplicationSettingsApplication?

    public init(app: SecurePasswordStoreApplicationSettingsApplication? = nil) {
        self.app = app
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case app
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(app, forKey: .app)
    }



}
