//
// SpCertificate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct SpCertificate: Codable, Hashable {

    public var x5c: [String]?

    public init(x5c: [String]? = nil) {
        self.x5c = x5c
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case x5c
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(x5c, forKey: .x5c)
    }



}
