//
// ApplicationCredentialsSigningUse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum ApplicationCredentialsSigningUse: String, Codable, CaseIterable, OktaClientArgument {
    case sig = "sig"

    var stringValue: String { rawValue }
}

