//
// Copyright (c) 2021-Present, Okta, Inc. and/or its affiliates. All rights reserved.
// The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
//
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and limitations under the License.
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct LogIpAddress: Codable, Hashable {

    public var geographicalContext: LogGeographicalContext?
    public var ip: String?
    public var source: String?
    public var version: String?

    public init(geographicalContext: LogGeographicalContext? = nil, ip: String? = nil, source: String? = nil, version: String? = nil) {
        self.geographicalContext = geographicalContext
        self.ip = ip
        self.source = source
        self.version = version
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case geographicalContext
        case ip
        case source
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(geographicalContext, forKey: .geographicalContext)
        try container.encodeIfPresent(ip, forKey: .ip)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(version, forKey: .version)
    }



}

