//
// OAuth2ScopeConsentGrantStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum OAuth2ScopeConsentGrantStatus: String, Codable, CaseIterable, OktaClientArgument {
    case active = "ACTIVE"
    case revoked = "REVOKED"

    var stringValue: String { rawValue }
}

