//
// OpenIdConnectApplicationConsentMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum OpenIdConnectApplicationConsentMethod: String, Codable, CaseIterable, OktaClientArgument {
    case _required = "REQUIRED"
    case trusted = "TRUSTED"

    var stringValue: String { rawValue }
}

