//
// PasswordPolicyRuleConditions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct PasswordPolicyRuleConditions: Codable/*, Hashable*/ {

    public var network: PolicyNetworkCondition?
    public var people: PolicyPeopleCondition?

    public init(network: PolicyNetworkCondition? = nil, people: PolicyPeopleCondition? = nil) {
        self.network = network
        self.people = people
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case network
        case people
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(network, forKey: .network)
        try container.encodeIfPresent(people, forKey: .people)
    }



}

