//
// PolicyAccountLinkFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct PolicyAccountLinkFilter: Codable, Hashable {

    public var groups: PolicyAccountLinkFilterGroups?

    public init(groups: PolicyAccountLinkFilterGroups? = nil) {
        self.groups = groups
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case groups
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(groups, forKey: .groups)
    }



}
