//
// RoleAssignmentType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum RoleAssignmentType: String, Codable, CaseIterable, OktaClientArgument {
    case group = "GROUP"
    case user = "USER"

    var stringValue: String { rawValue }
}

