//
// Copyright (c) 2021-Present, Okta, Inc. and/or its affiliates. All rights reserved.
// The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
//
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and limitations under the License.
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct TokenAuthorizationServerPolicyRuleAction: Codable, Hashable {

    public var accessTokenLifetimeMinutes: Int?
    public var inlineHook: TokenAuthorizationServerPolicyRuleActionInlineHook?
    public var refreshTokenLifetimeMinutes: Int?
    public var refreshTokenWindowMinutes: Int?

    public init(accessTokenLifetimeMinutes: Int? = nil, inlineHook: TokenAuthorizationServerPolicyRuleActionInlineHook? = nil, refreshTokenLifetimeMinutes: Int? = nil, refreshTokenWindowMinutes: Int? = nil) {
        self.accessTokenLifetimeMinutes = accessTokenLifetimeMinutes
        self.inlineHook = inlineHook
        self.refreshTokenLifetimeMinutes = refreshTokenLifetimeMinutes
        self.refreshTokenWindowMinutes = refreshTokenWindowMinutes
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessTokenLifetimeMinutes
        case inlineHook
        case refreshTokenLifetimeMinutes
        case refreshTokenWindowMinutes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accessTokenLifetimeMinutes, forKey: .accessTokenLifetimeMinutes)
        try container.encodeIfPresent(inlineHook, forKey: .inlineHook)
        try container.encodeIfPresent(refreshTokenLifetimeMinutes, forKey: .refreshTokenLifetimeMinutes)
        try container.encodeIfPresent(refreshTokenWindowMinutes, forKey: .refreshTokenWindowMinutes)
    }



}

