//
// Copyright (c) 2021-Present, Okta, Inc. and/or its affiliates. All rights reserved.
// The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
//
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and limitations under the License.
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct User: Codable, Hashable {

    public var embedded: [String: AnyCodable]?
    public var links: [String: AnyCodable]?
    public var activated: Date?
    public var created: Date?
    public var credentials: UserCredentials?
    public var id: String?
    public var lastLogin: Date?
    public var lastUpdated: Date?
    public var passwordChanged: Date?
    public var profile: UserProfile?
    public var status: UserStatus?
    public var statusChanged: Date?
    public var transitioningToStatus: UserStatus?
    public var type: UserType?

    public init(embedded: [String: AnyCodable]? = nil, links: [String: AnyCodable]? = nil, activated: Date? = nil, created: Date? = nil, credentials: UserCredentials? = nil, id: String? = nil, lastLogin: Date? = nil, lastUpdated: Date? = nil, passwordChanged: Date? = nil, profile: UserProfile? = nil, status: UserStatus? = nil, statusChanged: Date? = nil, transitioningToStatus: UserStatus? = nil, type: UserType? = nil) {
        self.embedded = embedded
        self.links = links
        self.activated = activated
        self.created = created
        self.credentials = credentials
        self.id = id
        self.lastLogin = lastLogin
        self.lastUpdated = lastUpdated
        self.passwordChanged = passwordChanged
        self.profile = profile
        self.status = status
        self.statusChanged = statusChanged
        self.transitioningToStatus = transitioningToStatus
        self.type = type
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case embedded = "_embedded"
        case links = "_links"
        case activated
        case created
        case credentials
        case id
        case lastLogin
        case lastUpdated
        case passwordChanged
        case profile
        case status
        case statusChanged
        case transitioningToStatus
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(embedded, forKey: .embedded)
        try container.encodeIfPresent(links, forKey: .links)
        try container.encodeIfPresent(activated, forKey: .activated)
        try container.encodeIfPresent(created, forKey: .created)
        try container.encodeIfPresent(credentials, forKey: .credentials)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(lastLogin, forKey: .lastLogin)
        try container.encodeIfPresent(lastUpdated, forKey: .lastUpdated)
        try container.encodeIfPresent(passwordChanged, forKey: .passwordChanged)
        try container.encodeIfPresent(profile, forKey: .profile)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(statusChanged, forKey: .statusChanged)
        try container.encodeIfPresent(transitioningToStatus, forKey: .transitioningToStatus)
        try container.encodeIfPresent(type, forKey: .type)
    }



}

