//
// ApplicationVisibility.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct ApplicationVisibility: Codable, Hashable {

    public var appLinks: [String: Bool]?
    public var autoSubmitToolbar: Bool?
    public var hide: ApplicationVisibilityHide?

    public init(appLinks: [String: Bool]? = nil, autoSubmitToolbar: Bool? = nil, hide: ApplicationVisibilityHide? = nil) {
        self.appLinks = appLinks
        self.autoSubmitToolbar = autoSubmitToolbar
        self.hide = hide
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case appLinks
        case autoSubmitToolbar
        case hide
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(appLinks, forKey: .appLinks)
        try container.encodeIfPresent(autoSubmitToolbar, forKey: .autoSubmitToolbar)
        try container.encodeIfPresent(hide, forKey: .hide)
    }



}
