//
// BookmarkApplicationSettingsApplication.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public final class BookmarkApplicationSettingsApplication: Codable, Hashable {

    public var requestIntegration: Bool?
    public var url: String?

    public init(requestIntegration: Bool? = nil, url: String? = nil) {
        self.requestIntegration = requestIntegration
        self.url = url
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requestIntegration
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(requestIntegration, forKey: .requestIntegration)
        try container.encodeIfPresent(url, forKey: .url)
    }



    public static func == (lhs: BookmarkApplicationSettingsApplication, rhs: BookmarkApplicationSettingsApplication) -> Bool {
        lhs.requestIntegration == rhs.requestIntegration &&
        lhs.url == rhs.url
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(requestIntegration?.hashValue)
        hasher.combine(url?.hashValue)
        
    }

}
