//
// InlineHookResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public final class InlineHookResponse: Codable, Hashable {

    public var commands: [InlineHookResponseCommands]?

    public init(commands: [InlineHookResponseCommands]? = nil) {
        self.commands = commands
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case commands
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(commands, forKey: .commands)
    }



    public static func == (lhs: InlineHookResponse, rhs: InlineHookResponse) -> Bool {
        lhs.commands == rhs.commands
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(commands?.hashValue)
        
    }

}
