//
// InlineHookResponseCommands.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public final class InlineHookResponseCommands: Codable, Hashable {

    public var type: String?
    public var value: [InlineHookResponseCommandValue]?

    public init(type: String? = nil, value: [InlineHookResponseCommandValue]? = nil) {
        self.type = type
        self.value = value
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(value, forKey: .value)
    }



    public static func == (lhs: InlineHookResponseCommands, rhs: InlineHookResponseCommands) -> Bool {
        lhs.type == rhs.type &&
        lhs.value == rhs.value
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(type?.hashValue)
        hasher.combine(value?.hashValue)
        
    }

}
