//
// LogDebugContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public final class LogDebugContext: Codable, Hashable {

    public var debugData: [String: AnyCodable]?

    public init(debugData: [String: AnyCodable]? = nil) {
        self.debugData = debugData
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case debugData
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(debugData, forKey: .debugData)
    }



    public static func == (lhs: LogDebugContext, rhs: LogDebugContext) -> Bool {
        lhs.debugData == rhs.debugData
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(debugData?.hashValue)
        
    }

}
