//
// PasswordPolicyRecoveryQuestionProperties.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public final class PasswordPolicyRecoveryQuestionProperties: Codable, Hashable {

    public var complexity: PasswordPolicyRecoveryQuestionComplexity?

    public init(complexity: PasswordPolicyRecoveryQuestionComplexity? = nil) {
        self.complexity = complexity
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case complexity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(complexity, forKey: .complexity)
    }



    public static func == (lhs: PasswordPolicyRecoveryQuestionProperties, rhs: PasswordPolicyRecoveryQuestionProperties) -> Bool {
        lhs.complexity == rhs.complexity
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(complexity?.hashValue)
        
    }

}
