//
// PlatformConditionEvaluatorPlatformOperatingSystemVersion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public final class PlatformConditionEvaluatorPlatformOperatingSystemVersion: Codable, Hashable {

    public enum MatchType: String, Codable, CaseIterable {
        case expression = "EXPRESSION"
        case semver = "SEMVER"
    }
    public var matchType: MatchType?
    public var value: String?

    public init(matchType: MatchType? = nil, value: String? = nil) {
        self.matchType = matchType
        self.value = value
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case matchType
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(matchType, forKey: .matchType)
        try container.encodeIfPresent(value, forKey: .value)
    }



    public static func == (lhs: PlatformConditionEvaluatorPlatformOperatingSystemVersion, rhs: PlatformConditionEvaluatorPlatformOperatingSystemVersion) -> Bool {
        lhs.matchType == rhs.matchType &&
        lhs.value == rhs.value
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(matchType?.hashValue)
        hasher.combine(value?.hashValue)
        
    }

}
