//
// SmsUserFactor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public final class SmsUserFactor: Codable, Hashable {

    public var profile: SmsUserFactorProfile?

    public init(profile: SmsUserFactorProfile? = nil) {
        self.profile = profile
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case profile
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(profile, forKey: .profile)
    }



    public static func == (lhs: SmsUserFactor, rhs: SmsUserFactor) -> Bool {
        lhs.profile == rhs.profile
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(profile?.hashValue)
        
    }

}
