name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  Xcode13.1:
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.1.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
